### ISSUE TITLE
Add Concordance metric

### ISSUE THREAD

**Issue by nikhil** [mskcc/collect-qc#24]
The Concordance function is used to make sure there are no sample mixups. This 

```
 concordance:
    function:
      match_sample_matrix:
        patient_regex: _._(.*)_.*_
        match_error_lt: 80
        match_warn_lt: 90
        unmatch_warn_gt: 50
        unmatch_error_gt: 70
```

Here is a concordance file that shows the samples as matched properly:

| concordance  |   s_C_Patient_1_X006_d05 | s_C_Patient_2_X005_d05  | s_C_Patient_1_G007_d06 |  s_C_Patient_2_G006_d06 |
| :-:| :-:| :-:| :-:| :-:|
s_C_Patient_1_N008_d07 |  100.0 |  48 |  100.0 |  41

while this is a concordance file indicating failure

Here is a concordance file that shows the samples did not match properly:

| concordance  |   s_C_Patient_1_X006_d05 | s_C_Patient_2_X005_d05  | s_C_Patient_1_G007_d06 |  s_C_Patient_2_G006_d06 |
| :-:| :-:| :-:| :-:| :-:|
s_C_Patient_1_N008_d07 |  100.0 | ![#f03c15](https://placehold.it/150/ffffff/ff0000?text=100) |  48 |  41
